symlink-sdk:
	mkdir -p vendor/sentry
	rm -rf vendor/sentry/sentry-symfony
	cd vendor/sentry && ln -sf ../../../.. sentry-symfony

	rm -rf vendor/sentry/sentry
	cd vendor/sentry && ln -sf ../../../../../sentry-php sentry
