version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "composer"
    directory: "/"
    allow:
      - dependency-name: "*phpstan*"
    schedule:
      interval: weekly
    groups:
      composer:
        patterns:
          - "*phpstan*"
